import { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";  // Import SessionProvider

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "VOTE SN TEACHERS",
  description: "Generated by KAUSHAL RAJPUT",
  icons: {
    icon: "/favicon.ico", // Path to your favicon
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" type="image/x-icon" />
      </head>
      <body className={inter.className}>
        <SessionProvider>{children}</SessionProvider>  {/* Wrap children with SessionProvider */}
      </body>
    </html>
  );
}
